package cn.coderss.user.mapper;

import cn.coderss.model.ActivityRelPeople;
import cn.coderss.model.ActivityRelPeopleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ActivityRelPeopleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_rel_people
     *
     * @mbggenerated Mon Dec 04 15:10:59 CST 2017
     */
    int countByExample(ActivityRelPeopleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_rel_people
     *
     * @mbggenerated Mon Dec 04 15:10:59 CST 2017
     */
    int deleteByExample(ActivityRelPeopleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_rel_people
     *
     * @mbggenerated Mon Dec 04 15:10:59 CST 2017
     */
    int deleteByPrimaryKey(Integer relid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_rel_people
     *
     * @mbggenerated Mon Dec 04 15:10:59 CST 2017
     */
    int insert(ActivityRelPeople record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_rel_people
     *
     * @mbggenerated Mon Dec 04 15:10:59 CST 2017
     */
    int insertSelective(ActivityRelPeople record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_rel_people
     *
     * @mbggenerated Mon Dec 04 15:10:59 CST 2017
     */
    List<ActivityRelPeople> selectByExample(ActivityRelPeopleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_rel_people
     *
     * @mbggenerated Mon Dec 04 15:10:59 CST 2017
     */
    ActivityRelPeople selectByPrimaryKey(Integer relid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_rel_people
     *
     * @mbggenerated Mon Dec 04 15:10:59 CST 2017
     */
    int updateByExampleSelective(@Param("record") ActivityRelPeople record, @Param("example") ActivityRelPeopleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_rel_people
     *
     * @mbggenerated Mon Dec 04 15:10:59 CST 2017
     */
    int updateByExample(@Param("record") ActivityRelPeople record, @Param("example") ActivityRelPeopleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_rel_people
     *
     * @mbggenerated Mon Dec 04 15:10:59 CST 2017
     */
    int updateByPrimaryKeySelective(ActivityRelPeople record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_rel_people
     *
     * @mbggenerated Mon Dec 04 15:10:59 CST 2017
     */
    int updateByPrimaryKey(ActivityRelPeople record);
}