package cn.coderss.user.mapper;

import cn.coderss.model.Mm;
import cn.coderss.model.MmExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mm
     *
     * @mbggenerated Mon Dec 04 15:10:59 CST 2017
     */
    int countByExample(MmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mm
     *
     * @mbggenerated Mon Dec 04 15:10:59 CST 2017
     */
    int deleteByExample(MmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mm
     *
     * @mbggenerated Mon Dec 04 15:10:59 CST 2017
     */
    int deleteByPrimaryKey(Integer activityid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mm
     *
     * @mbggenerated Mon Dec 04 15:10:59 CST 2017
     */
    int insert(Mm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mm
     *
     * @mbggenerated Mon Dec 04 15:10:59 CST 2017
     */
    int insertSelective(Mm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mm
     *
     * @mbggenerated Mon Dec 04 15:10:59 CST 2017
     */
    List<Mm> selectByExample(MmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mm
     *
     * @mbggenerated Mon Dec 04 15:10:59 CST 2017
     */
    Mm selectByPrimaryKey(Integer activityid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mm
     *
     * @mbggenerated Mon Dec 04 15:10:59 CST 2017
     */
    int updateByExampleSelective(@Param("record") Mm record, @Param("example") MmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mm
     *
     * @mbggenerated Mon Dec 04 15:10:59 CST 2017
     */
    int updateByExample(@Param("record") Mm record, @Param("example") MmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mm
     *
     * @mbggenerated Mon Dec 04 15:10:59 CST 2017
     */
    int updateByPrimaryKeySelective(Mm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mm
     *
     * @mbggenerated Mon Dec 04 15:10:59 CST 2017
     */
    int updateByPrimaryKey(Mm record);
}