package cn.coderss.model;

public class ActivityRelPeople {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_rel_people.relid
     *
     * @mbggenerated Mon Dec 04 15:10:59 CST 2017
     */
    private Integer relid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_rel_people.userid
     *
     * @mbggenerated Mon Dec 04 15:10:59 CST 2017
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_rel_people.activityid
     *
     * @mbggenerated Mon Dec 04 15:10:59 CST 2017
     */
    private Integer activityid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_rel_people.relid
     *
     * @return the value of activity_rel_people.relid
     *
     * @mbggenerated Mon Dec 04 15:10:59 CST 2017
     */
    public Integer getRelid() {
        return relid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_rel_people.relid
     *
     * @param relid the value for activity_rel_people.relid
     *
     * @mbggenerated Mon Dec 04 15:10:59 CST 2017
     */
    public void setRelid(Integer relid) {
        this.relid = relid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_rel_people.userid
     *
     * @return the value of activity_rel_people.userid
     *
     * @mbggenerated Mon Dec 04 15:10:59 CST 2017
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_rel_people.userid
     *
     * @param userid the value for activity_rel_people.userid
     *
     * @mbggenerated Mon Dec 04 15:10:59 CST 2017
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_rel_people.activityid
     *
     * @return the value of activity_rel_people.activityid
     *
     * @mbggenerated Mon Dec 04 15:10:59 CST 2017
     */
    public Integer getActivityid() {
        return activityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_rel_people.activityid
     *
     * @param activityid the value for activity_rel_people.activityid
     *
     * @mbggenerated Mon Dec 04 15:10:59 CST 2017
     */
    public void setActivityid(Integer activityid) {
        this.activityid = activityid;
    }
}