package cn.coderss.model;

public class Activity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.activityid
     *
     * @mbggenerated Mon Dec 04 15:10:59 CST 2017
     */
    private Integer activityid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.title
     *
     * @mbggenerated Mon Dec 04 15:10:59 CST 2017
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.time
     *
     * @mbggenerated Mon Dec 04 15:10:59 CST 2017
     */
    private String time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.address
     *
     * @mbggenerated Mon Dec 04 15:10:59 CST 2017
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.pic
     *
     * @mbggenerated Mon Dec 04 15:10:59 CST 2017
     */
    private String pic;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.activityid
     *
     * @return the value of activity.activityid
     *
     * @mbggenerated Mon Dec 04 15:10:59 CST 2017
     */
    public Integer getActivityid() {
        return activityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.activityid
     *
     * @param activityid the value for activity.activityid
     *
     * @mbggenerated Mon Dec 04 15:10:59 CST 2017
     */
    public void setActivityid(Integer activityid) {
        this.activityid = activityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.title
     *
     * @return the value of activity.title
     *
     * @mbggenerated Mon Dec 04 15:10:59 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.title
     *
     * @param title the value for activity.title
     *
     * @mbggenerated Mon Dec 04 15:10:59 CST 2017
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.time
     *
     * @return the value of activity.time
     *
     * @mbggenerated Mon Dec 04 15:10:59 CST 2017
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.time
     *
     * @param time the value for activity.time
     *
     * @mbggenerated Mon Dec 04 15:10:59 CST 2017
     */
    public void setTime(String time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.address
     *
     * @return the value of activity.address
     *
     * @mbggenerated Mon Dec 04 15:10:59 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.address
     *
     * @param address the value for activity.address
     *
     * @mbggenerated Mon Dec 04 15:10:59 CST 2017
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.pic
     *
     * @return the value of activity.pic
     *
     * @mbggenerated Mon Dec 04 15:10:59 CST 2017
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.pic
     *
     * @param pic the value for activity.pic
     *
     * @mbggenerated Mon Dec 04 15:10:59 CST 2017
     */
    public void setPic(String pic) {
        this.pic = pic;
    }
}