package cn.coderss.model;

public class Class {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.classid
     *
     * @mbggenerated Mon Dec 04 15:10:59 CST 2017
     */
    private Integer classid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.name
     *
     * @mbggenerated Mon Dec 04 15:10:59 CST 2017
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.classid
     *
     * @return the value of class.classid
     *
     * @mbggenerated Mon Dec 04 15:10:59 CST 2017
     */
    public Integer getClassid() {
        return classid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.classid
     *
     * @param classid the value for class.classid
     *
     * @mbggenerated Mon Dec 04 15:10:59 CST 2017
     */
    public void setClassid(Integer classid) {
        this.classid = classid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.name
     *
     * @return the value of class.name
     *
     * @mbggenerated Mon Dec 04 15:10:59 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.name
     *
     * @param name the value for class.name
     *
     * @mbggenerated Mon Dec 04 15:10:59 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }
}