package cn.coderss.model;

public class Mm {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mm.activityid
     *
     * @mbggenerated Mon Dec 04 15:10:59 CST 2017
     */
    private Integer activityid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mm.name
     *
     * @mbggenerated Mon Dec 04 15:10:59 CST 2017
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mm.activityid
     *
     * @return the value of mm.activityid
     *
     * @mbggenerated Mon Dec 04 15:10:59 CST 2017
     */
    public Integer getActivityid() {
        return activityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mm.activityid
     *
     * @param activityid the value for mm.activityid
     *
     * @mbggenerated Mon Dec 04 15:10:59 CST 2017
     */
    public void setActivityid(Integer activityid) {
        this.activityid = activityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mm.name
     *
     * @return the value of mm.name
     *
     * @mbggenerated Mon Dec 04 15:10:59 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mm.name
     *
     * @param name the value for mm.name
     *
     * @mbggenerated Mon Dec 04 15:10:59 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }
}