package cn.coderss.model;

public class Student {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stuid
     *
     * @mbggenerated Mon Dec 04 15:10:59 CST 2017
     */
    private Integer stuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.name
     *
     * @mbggenerated Mon Dec 04 15:10:59 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.classid
     *
     * @mbggenerated Mon Dec 04 15:10:59 CST 2017
     */
    private Integer classid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stuid
     *
     * @return the value of student.stuid
     *
     * @mbggenerated Mon Dec 04 15:10:59 CST 2017
     */
    public Integer getStuid() {
        return stuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stuid
     *
     * @param stuid the value for student.stuid
     *
     * @mbggenerated Mon Dec 04 15:10:59 CST 2017
     */
    public void setStuid(Integer stuid) {
        this.stuid = stuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.name
     *
     * @return the value of student.name
     *
     * @mbggenerated Mon Dec 04 15:10:59 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.name
     *
     * @param name the value for student.name
     *
     * @mbggenerated Mon Dec 04 15:10:59 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.classid
     *
     * @return the value of student.classid
     *
     * @mbggenerated Mon Dec 04 15:10:59 CST 2017
     */
    public Integer getClassid() {
        return classid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.classid
     *
     * @param classid the value for student.classid
     *
     * @mbggenerated Mon Dec 04 15:10:59 CST 2017
     */
    public void setClassid(Integer classid) {
        this.classid = classid;
    }
}